version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 14-buster
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    networks:
      - dev-network

  db:
    image: mongo:7.0
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    networks:
      - dev-network

volumes:
  mongodb-data:

networks:
  dev-network:

